### ISSUE TITLE
queue_unbind error

### ISSUE THREAD

**Issue by christiancadieux** [paolo-losi/stormed-amqp#23]
queue_unbind takes the following arguments, but nowait is not allowed:
def queue_bind(self, queue, exchange, routing_key='', callback=None):
        self.send_method(_queue.Bind(ticket      = 0,
                                     queue       = queue,
                                     exchange    = exchange,
                                     routing_key = routing_key,
                                     nowait      = False,
                                     arguments   = dict()), callback)

File "/opt/ZN/Packages/stormed/channel.py", line 120, in queue_unbind
    arguments   = dict()), callback)
  File "/opt/ZN/Packages/stormed/util.py", line 25, in __init__
    raise AttributeError('invalid field name/s: %s' % unvalid_kargs)
AttributeError: invalid field name/s: set(['nowait'])

**Comment by paolo-losi** [comment]
Hi @christiancadieux, let me check this ...
